### ISSUE TITLE
Broken demo, pixi-tilemap.js 404

### ISSUE THREAD

**Issue by Zetaphor** [Alan01252/pixi-tilemap-tutorial#1]
The demo on your site is currently broken because of [PR #28 on pixi-tilemap](https://github.com/pixijs/pixi-tilemap/pull/28).

A hosted copy can be found [here](https://pixijs.github.io/pixi-tilemap/bin/pixi-tilemap.js).

**Comment by crazyyi** [comment]
Same error. Demo not working.

**Comment by Alan01252** [comment]
Resolved by https://github.com/Alan01252/pixi-tilemap-tutorial/pull/3
